### ISSUE TITLE
Milestone 0.2.0/userscript

### ISSUE THREAD

**Issue by simonpai** [simonpai/hammermonkey#6]
Feature
- [x] Delete session
- [x] Confirm dialog for deletion
- [x] Rule active state control
- [x] Persist UI state

Refactoring
- [x] Settle down UI terminology
- [x] Refactor redux structure
- [x] Components get everything through selector
- [x] Clean up inline styles
